env:
  TERM: xterm-256color
window:
  decorations: buttonless
  padding:
    x: 2
    y: 2
font:
  normal:
    family: "Hack Nerd Font"
    style: Regular
  bold:
    family: "Hack Nerd Font"
    style: Bold
  italic:
    family: "Hack Nerd Font"
    style: Italic
  bold_italic:
    family: "Hack Nerd Font"
    style: Bold Italic
  size: 16.0
bell:
  animation: EaseOutCirc
  duration: 10
  color: '#aaaaaa'
background_opacity: 0.93
colors: # (Monokaish)
  # Default colors
  primary:
    background: '#0a0a0a'
    foreground: '#c4c5b5'
  # Normal colors
  normal:
    black:   '#0e0e0e'
    red:     '#e54375'
    green:   '#98e024'
    yellow:  '#eedf64'
    blue:    '#a684f7'
    magenta: '#fa8419'
    cyan:    '#58d1eb'
    white:   '#c4c5b5'
  # Bright colors
  bright:
    black:   '#625e4c'
    red:     '#e54375'
    green:   '#98e024'
    yellow:  '#eedf54'
    blue:    '#a684f7'
    magenta: '#fa8419'
    cyan:    '#58d1eb'
    white:   '#f6f6ef'
  search:
    matches:
      foreground: '#000000'
      background: '#ffffff'
scrolling:
  history: 100000
  multiplier: 3
cursor:
  style:
    shape: Block
    blinking: On
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
  url:
    launcher:
      program: open
mouse_bindings:
  - { mouse: Middle, action: Copy}
