layouts:
  - tall
  - fullscreen
  - two-pane
  - middle-wide
  - floating
mod1:
  - control
  - option
mod2:
  - option
mod3:
  - option
  - shift
cycle-layout:
  mod: mod2
  key: space
cycle-layout-backward:
  mod: mod3
  key: space

# Shrink the main pane by a percentage of the screen dimension as defined by window-resize-step. Note that not all layouts respond to this command.
shrink-main:
  mod: mod1
  key: h

# Expand the main pane by a percentage of the screen dimension as defined by window-resize-step. Note that not all layouts respond to this command.
expand-main:
  mod: mod1
  key: l

# Focus the next window in the list going counter-clockwise.
focus-ccw:
  mod: mod1
  key: j

# Focus the next window in the list going clockwise.
focus-cw:
  mod: mod1
  key: k

# Focus the main window in the list.
focus-main:
  mod: mod1
  key: m


# Focus the next screen in the list going counter-clockwise.
focus-screen-ccw:
  mod: mod1
  key: p

# Focus the next screen in the list going clockwise.
focus-screen-cw:
  mod: mod1
  key: n

# Swap the position of the currently focused window with the next window in the list going counter-clockwise.
swap-ccw:
  mod: mod1
  key: u

# Swap the position of the currently focused window with the next window in the list going clockwise.
swap-cw:
  mod: mod1
  key: i

# Swap the position of the currently focused window with the main window in the list.
swap-main:
  mod: mod2
  key: enter

# Select tall layout
select-tall-layout:
  mod: mod1
  key: a

# Select fullscreen layout
select-fullscreen-layout:
  mod: mod1
  key: s

# Select floating layout
select-floating-layout:
  mod: mod1
  key: f

# Move the currently focused window to the space to the left.
throw-space-left:
  mod: mod2
  key: left

# Move currently the focused window to the space to the right.
throw-space-right:
  mod: mod2
  key: right

# Turn on or off tiling entirely.
toggle-tiling:
  mod: mod1
  key: t

# Boolean flag for whether or not to add margins betwen windows (default false).
window-margins: false

# Boolean flag for whether or not to set window margins if there is only one window on the screen, assuming window margins are enabled (default false).
smart-window-margins: true
window-margin-size: 0
