layouts:
  - tall
  - floating
  - fullscreen

mod1:
  - control
  - option

cycle-layout:
  mod: mod1
  key: space

# Shrink the main pane by a percentage of the screen dimension as defined by window-resize-step. Note that not all layouts respond to this command.
shrink-main:
  mod: mod1
  key: h

# Expand the main pane by a percentage of the screen dimension as defined by window-resize-step. Note that not all layouts respond to this command.
expand-main:
  mod: mod1
  key: l

# Focus the next window in the list going counter-clockwise.
focus-ccw:
  mod: mod1
  key: k

# Focus the next window in the list going clockwise.
focus-cw:
  mod: mod1
  key: j

# Focus the main window in the list.
focus-main:
  mod: mod1
  key: m

# Focus the next screen in the list going counter-clockwise.
focus-screen-ccw:
  mod: mod1
  key: p

# Focus the next screen in the list going clockwise.
focus-screen-cw:
  mod: mod1
  key: n

# Swap the position of the currently focused window with the next window in the list going counter-clockwise.
swap-ccw:
  mod: mod1
  key: u

# Swap the position of the currently focused window with the next window in the list going clockwise.
swap-cw:
  mod: mod1
  key: i

# Swap the position of the currently focused window with the main window in the list.
swap-main:
  mod: mod1
  key: enter

# Move the currently focused window to the space to the left.
throw-space-left:
  mod: mod1
  key: left

# Move currently the focused window to the space to the right.
throw-space-right:
  mod: mod1
  key: right

# Turn on or off tiling entirely.
toggle-tiling:
  mod: mod1
  key: t

# Move to previous screen.
swap-screen-ccw:
  mod: mod1
  key: '['

# Move to next screen.
swap-screen-cw:
  mod: mod1
  key: ']'

# Throw windows to spaces.
throw-space-1:
  mod: mod1
  key: '1'

throw-space-2:
  mod: mod1
  key: '2'

throw-space-3:
  mod: mod1
  key: '3'

throw-space-4:
  mod: mod1
  key: '4'

throw-space-5:
  mod: mod1
  key: '5'

throw-space-6:
  mod: mod1
  key: '6'

throw-space-7:
  mod: mod1
  key: '7'

# Boolean flag for whether or not to add margins betwen windows (default false).
window-margins: true

# Boolean flag for whether or not to set window margins if there is only one window on the screen, assuming window margins are enabled (default false).
smart-window-margins: true
window-margin-size: 5
